### PR TITLE
Mark module as deprecated.

### PR DESCRIPTION
**Pull request by oalders**
@neilbowers let me know that this module should be marked as deprecated, which this pull request takes care of.  If you're short on time to cut a new release, you can assign co-maint to me (OALDERS) and I can release the deprecated version for you.

### CODE REVIEW

**Comment by frodwith** [comment]
This isn't my module, it belongs to nperez. I can't give you comaint and
it's inaccurate to point at my github repo.

**Comment by sergeyromanov** [comment]
> it's inaccurate to point at my github repo.

According to [BackPAN](http://backpan.perl.org/authors/id/F/FR/FRODWITH/) you were in charge for most of this dist's releases, which makes you a first stop for other people to send patches/PRs. There's generally nothing wrong with updating metadata with your GitHub repo's URL and it simplifies contributing. I'm also almost sure @nperez would not strongly disprove it :)

**Comment by frodwith** [comment]
You should definitely believe some data you mined instead of someone who is
personally involved. Good luck solving this issue on your own.

**Comment by oalders** [comment]
Forget the co-maint thing. Was just trying to be helpful. Your repo looked
to be the most up to date. The nperez repo is clearly out of sync with the
CPAN releases.

Sent from my iPhone

On Jan 17, 2015, at 11:39, Paul Driver notifications@github.com wrote:

This isn't my module, it belongs to nperez. I can't give you comaint and
it's inaccurate to point at my github repo.

**Comment by oalders** [comment]
I'm closing this pull request as it seems pointless now.  For the record, @frodwith, your response to @sergeyromanov comes off as rude and perhaps even openly hostile.  If you didn't mean it to be that way, you may want to qualify your remarks.  As it stands, this really just seems like a poor and unfortunate way to handle the conversation.

**Comment by frodwith** [comment]
I am sorry for being rude.

**Comment by sergeyromanov** [comment]
That's okay. We're just a bunch of people hoping to make CPAN a bit of a nicer place (e.g. by removing deprecated/long-time broken stuff).

**Comment by oalders** [comment]
:)

**Pull request closed without merging**
